/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DerecCryptoBridge */

#ifndef _Included_DerecCryptoBridge
#define _Included_DerecCryptoBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DerecCryptoBridge
 * Method:    share
 * Signature: ([B)[B
 */
JNIEXPORT jbytearray JNICALL Java_DerecCryptoBridge_share
  (JNIEnv *, jclass, jint, jint, jbyteArray, jbyteArray, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
